services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api:v7.2.2-s.4
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: v7.2.2-s.4
        COMMIT: ${COMMIT:-none}
        BUILD_DATE: "2026/05/30 08:08:59"
    container_name: cli-proxy-api
    network_mode: host
    # env_file:
    #   - .env
    environment:
      DEPLOY: ${DEPLOY:-}
      MANAGEMENT_PASSWORD: skloxoskloxoskloxo
    ports:
      - "8317:8317"
      - "8085:8085"
      - "1455:1455"
      - "54545:54545"
      - "51121:51121"
      - "11451:11451"
    user: "root"
    volumes:
      - ${CLI_PROXY_CONFIG_PATH:-./config.yaml}:/app/config.yaml
      - ${CLI_PROXY_AUTH_PATH:-./auths}:/root/.cli-proxy-api
      - ${CLI_PROXY_LOG_PATH:-./logs}:/app/logs
      - ./static:/app/static
      - ./cpa-manager-database-backup.tar.gz:/app/cpa-manager-database-backup.tar.gz:ro
    restart: unless-stopped
